all:
	gcc -o serverHTTP-REST 			  	serverHTTP-REST.c 		  	   network.c -I.
	gcc -o serverHTTP-REST_es_finale1 	serverHTTP-REST_es_finale1.c   network.c -I.
	gcc -o serverHTTP-REST_es_finale2 	serverHTTP-REST_es_finale2.c   network.c -I.
	gcc -o ClientREST-GET 			  	ClientREST-GET.c 			   network.c -I.
	gcc -o ClientREST-POST 			  	ClientREST-POST.c 		       network.c -I.

clean:
	rm -rf serverHTTP-REST
	rm -rf serverHTTP-REST_es_finale1
	rm -rf serverHTTP-REST_es_finale2
	rm -rf ClientREST-GET
	rm -rf ClientREST-POST
